#!/bin/bash
# $Id: webupd,v 1.50 2017/05/22 19:32:44 fulford Exp fulford $
# $Source: /src/admin/usr/local/etc/RCS/webupd,v $
# $Revision: 1.50 $
# Author C W Fulford.
# Copyright (c) 2012-2013 C W Fulford. 
# Licensed for public use under the LGPL.
# For assistance contact fulford@fulford.net 0709 229 5385
###################################################################
debug=0
cmd=`basename $0`
#set -x
syntax="$cmd [[-c <config_file>] [-d] [[-h]|[-s]] [-S] [-v] <host_name>]|[-V]" 
updates="awstats htdig"
verbose=0
error=`echo $cmd|awk  '/-h/&&/-s/{print "0"}'`
error=${error:=1}
[ $error -eq 0 ] &&{
	echo "$syntax" 
	exit 1 
}
while [ $# -gt 0 ];do
	case $1 in
		-S) static="-staticlinks";shift;;
		-c) config=$2;shift 2;;
		-d) debug=1; set -x;shift ;;
		-h) updates=htdig; shift ;;
		-s) updates=awstats; shift ;;
		-v) verbose=1 ;shift 1;;
		-V) echo "$cmd $Revision: 1.50 $"|awk '{print $1,$3}';exit;;  
		 *) host=$1;shift;;
	esac
done
[ -z $host ] && { echo "syntax: $syntax">&2;exit 1 ;}
config=${config:-/usr/local/etc/webupd.cf}
if [ -r $config ];then
	[ $verbose -gt 0 ] && echo "config = $config"
	eval `sed -ne  '/^'$host':$/,/^$/{/^[ \t].*[^#]/p}' <$config `
else
	echo "$cmd can't find $config">&2
	exit 1
fi
[ $verbose -gt 0 ] && echo "$cmd: updating awstats on $host" 
if echo $updates|grep -q "awstats";then 	
	for s in $sites ;do
		[ $verbose -gt 0 ] &&{
			 echo -n "updating awstats for $s on $host" 
		}
		ssh -q $host "cd $awstats/cgi-bin;sudo perl awstats.pl -config=$s -update -output $static |sudo dd of=$wwwroot/$s/awstats.html &2>/dev/null"
		[ $verbose -gt 0 ] && echo " - done." 
	done
fi
if echo $updates|grep -q "htdig";then
		[ $verbose -gt 0 ] && {
			echo "updating dig for $dig_cf on $host" 
		}
		ssh -q $host "
		for conf in $dig_cf;do
			[ $verbose -gt 0 ] &&{
				 echo "updating dig using \$conf"
			}
			sudo rundig -c /etc/htdig/\$conf;
		done"
fi
